import {
  User,
  Guard,
  DeploymentPost,
  Incident,
  PayrollEntry,
  BoardMember,
  CompanyInfo,
  MeritScore,
  Contact,
} from './types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Mensah',
    email: 'john.mensah@skones.com',
    phone: '+233 302 781591',
    role: 'admin',
    lastLogin: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Ama Owusu',
    email: 'ama.owusu@skones.com',
    phone: '+233 244 624109',
    role: 'accounts',
    lastLogin: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Kwame Boateng',
    email: 'kwame.boateng@skones.com',
    phone: '+233 501 234567',
    role: 'operations',
    lastLogin: new Date().toISOString(),
  },
];

// Mock Guards
export const mockGuards: Guard[] = [
  {
    id: 'G001',
    name: 'Kofi Asante',
    email: 'kofi.asante@skones.com',
    phone: '+233 501 111111',
    idNumber: 'GH-2024-001',
    dateOfHire: '2020-03-15',
    status: 'on_duty',
    currentDeploymentPostId: 'P001',
    meritScore: 92,
    certifications: ['First Aid', 'Security Training'],
    lastCheckIn: new Date().toISOString(),
  },
  {
    id: 'G002',
    name: 'Yaw Mensah',
    email: 'yaw.mensah@skones.com',
    phone: '+233 501 222222',
    idNumber: 'GH-2024-002',
    dateOfHire: '2021-06-20',
    status: 'on_duty',
    currentDeploymentPostId: 'P002',
    meritScore: 85,
    certifications: ['Security Training'],
    lastCheckIn: new Date().toISOString(),
  },
  {
    id: 'G003',
    name: 'Abena Osei',
    email: 'abena.osei@skones.com',
    phone: '+233 501 333333',
    idNumber: 'GH-2024-003',
    dateOfHire: '2022-01-10',
    status: 'off_duty',
    meritScore: 78,
    certifications: ['Security Training', 'CPR'],
    lastCheckIn: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'G004',
    name: 'Samuel Okonkwo',
    email: 'samuel.okonkwo@skones.com',
    phone: '+233 501 444444',
    idNumber: 'GH-2024-004',
    dateOfHire: '2019-11-05',
    status: 'on_duty',
    currentDeploymentPostId: 'P001',
    meritScore: 95,
    certifications: ['First Aid', 'Security Training', 'Advanced Combat'],
    lastCheckIn: new Date().toISOString(),
  },
  {
    id: 'G005',
    name: 'Ama Boateng',
    email: 'ama.boateng@skones.com',
    phone: '+233 501 555555',
    idNumber: 'GH-2024-005',
    dateOfHire: '2023-02-14',
    status: 'on_leave',
    meritScore: 88,
    certifications: ['Security Training'],
    lastCheckIn: new Date(Date.now() - 172800000).toISOString(),
  },
];

// Mock Deployment Posts
export const mockDeploymentPosts: DeploymentPost[] = [
  {
    id: 'P001',
    name: 'Accra Business District - Main Office',
    location: 'Accra',
    address: '123 High Street, Accra, Ghana',
    latitude: 5.6037,
    longitude: -0.187,
    clientName: 'Accra Business Hub',
    clientContact: 'Mr. Kwesi Amoah',
    clientEmail: 'kwesi@businesshub.com',
    status: 'active',
    guardsRequired: 3,
    assignedGuards: ['G001', 'G004'],
    shiftStart: '06:00',
    shiftEnd: '18:00',
    createdDate: '2023-01-15',
    lastActivityTime: new Date().toISOString(),
  },
  {
    id: 'P002',
    name: 'Tema Port Authority',
    location: 'Tema',
    address: '456 Port Road, Tema, Ghana',
    latitude: 5.6037,
    longitude: -0.0167,
    clientName: 'Tema Port Authority',
    clientContact: 'Capt. Ama Mensah',
    clientEmail: 'ama.mensah@tema-port.gov.gh',
    status: 'active',
    guardsRequired: 5,
    assignedGuards: ['G002'],
    shiftStart: '00:00',
    shiftEnd: '23:59',
    createdDate: '2023-02-20',
    lastActivityTime: new Date().toISOString(),
  },
  {
    id: 'P003',
    name: 'Kumasi Shopping Mall',
    location: 'Kumasi',
    address: '789 Commerce Street, Kumasi, Ghana',
    latitude: 6.6753,
    longitude: -1.6167,
    clientName: 'Kumasi Shopping Mall',
    clientContact: 'Ms. Yaa Asiedu',
    clientEmail: 'yaa@kumasi-mall.com',
    status: 'inactive',
    guardsRequired: 4,
    assignedGuards: [],
    shiftStart: '09:00',
    shiftEnd: '21:00',
    createdDate: '2023-03-10',
  },
];

// Mock Merit Scores
export const mockMeritScores: MeritScore[] = [
  {
    guardId: 'G001',
    overall: 92,
    attendance: 95,
    performance: 90,
    conduct: 92,
    trainingCompletion: 88,
    lastUpdated: new Date().toISOString(),
    history: [
      {
        date: new Date(Date.now() - 604800000).toISOString(),
        category: 'attendance',
        change: 2,
        reason: 'Perfect attendance for the week',
      },
      {
        date: new Date(Date.now() - 1209600000).toISOString(),
        category: 'performance',
        change: 1,
        reason: 'Excellent incident response',
      },
    ],
  },
];

// Mock Incidents
export const mockIncidents: Incident[] = [
  {
    id: 'INC001',
    type: 'breach',
    description: 'Unauthorized person attempted to enter restricted area',
    location: 'Main Gate - Accra Business District',
    latitude: 5.6037,
    longitude: -0.187,
    dateTime: new Date(Date.now() - 86400000).toISOString(),
    reportedBy: 'G001',
    guardIds: ['G001', 'G004'],
    severity: 'high',
    status: 'resolved',
    photos: [],
    attachments: [],
    timeline: [
      {
        timestamp: new Date(Date.now() - 86400000).toISOString(),
        updatedBy: 'G001',
        status: 'reported',
        notes: 'Breach attempt detected at main gate',
      },
      {
        timestamp: new Date(Date.now() - 82800000).toISOString(),
        updatedBy: 'admin',
        status: 'investigating',
        notes: 'Investigation initiated',
      },
      {
        timestamp: new Date(Date.now() - 79200000).toISOString(),
        updatedBy: 'admin',
        status: 'resolved',
        notes: 'Intruder apprehended and handed to police',
      },
    ],
    resolutionNotes: 'Intruder was apprehended and handed to police. Enhanced security measures implemented.',
    resolvedDate: new Date(Date.now() - 79200000).toISOString(),
  },
  {
    id: 'INC002',
    type: 'equipment_damage',
    description: 'CCTV camera damaged at north entrance',
    location: 'North Entrance - Accra Business District',
    latitude: 5.6047,
    longitude: -0.188,
    dateTime: new Date(Date.now() - 172800000).toISOString(),
    reportedBy: 'G004',
    guardIds: ['G004'],
    severity: 'medium',
    status: 'closed',
    photos: [],
    attachments: [],
    timeline: [
      {
        timestamp: new Date(Date.now() - 172800000).toISOString(),
        updatedBy: 'G004',
        status: 'reported',
        notes: 'CCTV camera damaged',
      },
      {
        timestamp: new Date(Date.now() - 169200000).toISOString(),
        updatedBy: 'admin',
        status: 'resolved',
        notes: 'Replacement camera ordered',
      },
    ],
    resolutionNotes: 'Camera replaced. Maintenance schedule updated.',
    resolvedDate: new Date(Date.now() - 169200000).toISOString(),
  },
];

// Mock Payroll Entries
export const mockPayrollEntries: PayrollEntry[] = [
  {
    id: 'PAY001',
    guardId: 'G001',
    guardName: 'Kofi Asante',
    period: '2026-05-01 to 2026-05-31',
    daysWorked: 22,
    hoursWorked: 176,
    hourlyRate: 25,
    overtimeHours: 8,
    overtimeRate: 37.5,
    deductions: 50,
    totalAmount: 4650,
    status: 'approved',
    approvedBy: 'Ama Owusu',
    approvalDate: new Date().toISOString(),
  },
  {
    id: 'PAY002',
    guardId: 'G002',
    guardName: 'Yaw Mensah',
    period: '2026-05-01 to 2026-05-31',
    daysWorked: 20,
    hoursWorked: 160,
    hourlyRate: 25,
    overtimeHours: 0,
    overtimeRate: 37.5,
    deductions: 0,
    totalAmount: 4000,
    status: 'pending',
  },
  {
    id: 'PAY003',
    guardId: 'G004',
    guardName: 'Samuel Okonkwo',
    period: '2026-05-01 to 2026-05-31',
    daysWorked: 23,
    hoursWorked: 184,
    hourlyRate: 30,
    overtimeHours: 12,
    overtimeRate: 45,
    deductions: 75,
    totalAmount: 6165,
    status: 'paid',
    approvedBy: 'Ama Owusu',
    approvalDate: new Date(Date.now() - 259200000).toISOString(),
    paidDate: new Date(Date.now() - 172800000).toISOString(),
  },
];

// Mock Board Members
export const mockBoardMembers: BoardMember[] = [
  {
    id: 'B001',
    name: 'Alhaji Iddi Sumaila',
    title: 'Group Executive Director & Founder',
    photo: '',
    bio: 'Founder and CEO with 23+ years of entrepreneurial experience. Established Skones Ghana Limited as a Construction Company in 1996 and grew it into a leading security services provider.',
    email: 'iddi.sumaila@skones.com',
    phone: '+233 302 781591',
  },
  {
    id: 'B002',
    name: 'Charles Martinson',
    title: 'Managing Director',
    photo: '',
    bio: 'Security Management professional with 25+ years of experience. Diploma in Banking (IBS), Diploma in Management Studies (IIM), currently pursuing MSc in Security Management.',
    email: 'charles.martinson@skones.com',
    phone: '+233 244 624109',
  },
  {
    id: 'B003',
    name: 'Asumana Alhassan',
    title: 'Director of Operations',
    photo: '',
    bio: 'Oversees all operational aspects of security deployments and guard management across Ghana.',
    email: 'asumana.alhassan@skones.com',
    phone: '+233 501 234567',
  },
  {
    id: 'B004',
    name: 'Baffour Agyemang',
    title: 'Finance Director',
    photo: '',
    bio: 'Manages financial operations, payroll, and accounting for the organization.',
    email: 'baffour.agyemang@skones.com',
    phone: '+233 501 234568',
  },
  {
    id: 'B005',
    name: 'Stephen Akoto Boadi',
    title: 'Technical Director',
    photo: '',
    bio: 'Oversees technology infrastructure, electronic security systems, and digital transformation.',
    email: 'stephen.boadi@skones.com',
    phone: '+233 501 234569',
  },
];

// Mock Company Info
export const mockCompanyInfo: CompanyInfo = {
  name: 'Skones Security Limited',
  foundedYear: 1999,
  description:
    'Skones Security Limited is a wholly Ghanaian-owned company providing professional security services since 1999. We provide security services for both individuals and corporate entities, including guard/patrol services, cash in transit, and electronic security systems.',
  mission:
    'To provide maximum professional and cost-effective security services to businesses, organizations, individuals, and communities to complement the efforts of government in providing safety and security for the citizenry.',
  vision: 'To be the leading security services provider in West Africa',
  values: ['Integrity', 'Excellence', 'People', 'Clients', 'Learning', 'Community'],
  headquarters: {
    address: 'Accra, Ghana',
    city: 'Accra',
    phone: '+233 302 781591 / +233 244 624109',
    email: 'info@skonesecurity.com',
  },
  socialMedia: {
    facebook: 'https://www.facebook.com/Skonesec',
    instagram: 'https://www.instagram.com/skonesecurity',
    tiktok: 'https://www.tiktok.com/@skonesecurity',
    whatsapp: 'https://wa.me/233501234567',
  },
  services: [
    {
      id: 'S001',
      name: 'Security Guard Services',
      description: 'Professional security personnel providing 24/7 protection at private and public places across Ghana.',
      icon: 'shield.fill',
    },
    {
      id: 'S002',
      name: 'Escort & Bullion Services',
      description: 'Secure cash collection, specie movement, and transportation of valuables for banks and retailers.',
      icon: 'car.fill',
    },
    {
      id: 'S003',
      name: 'Electronic Systems Services',
      description: 'Installation and maintenance of CCTV, access control, alarm systems, and other security technologies.',
      icon: 'camera.fill',
    },
    {
      id: 'S004',
      name: 'Cash-in-Transit Services',
      description: 'Specialized secure transportation of cash and valuables with real-time tracking.',
      icon: 'briefcase.fill',
    },
  ],
  boardMembers: mockBoardMembers,
  history: [
    {
      year: 1999,
      title: 'Company Founded',
      description: 'Skones Security Limited established and registered under Companies Code 1963 (Act 179).',
    },
    {
      year: 2005,
      title: 'APSOG Founding Member',
      description: 'Became one of the founding members of Association of Private Security Organizations Ghana.',
    },
    {
      year: 2010,
      title: 'Expansion Across Ghana',
      description: 'Expanded operations to major cities including Kumasi, Tema, and Takoradi.',
    },
    {
      year: 2015,
      title: 'Technology Integration',
      description: 'Implemented advanced GPS tracking and communication systems for guard management.',
    },
    {
      year: 2020,
      title: 'Workforce Growth',
      description: 'Expanded workforce to over 1,200 trained security personnel.',
    },
    {
      year: 2024,
      title: 'Digital Transformation',
      description: 'Launched Skones Security Management App for enhanced operations and guard monitoring.',
    },
  ],
};

// Mock Contacts
export const mockContacts: Contact[] = [
  {
    id: '1',
    name: 'John Mensah',
    role: 'admin',
    phone: '+233 501 111111',
    email: 'john.mensah@skones.com',
    status: 'online',
  },
  {
    id: '2',
    name: 'Ama Owusu',
    role: 'accounts',
    phone: '+233 501 222222',
    email: 'ama.owusu@skones.com',
    status: 'online',
  },
  {
    id: '3',
    name: 'Kwame Boateng',
    role: 'operations',
    phone: '+233 501 333333',
    email: 'kwame.boateng@skones.com',
    status: 'away',
    lastSeen: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'G001',
    name: 'Kofi Asante',
    role: 'guard',
    phone: '+233 501 111111',
    email: 'kofi.asante@skones.com',
    status: 'online',
  },
  {
    id: 'G002',
    name: 'Yaw Mensah',
    role: 'guard',
    phone: '+233 501 222222',
    email: 'yaw.mensah@skones.com',
    status: 'online',
  },
];
